### ISSUE TITLE
Virus ?

### ISSUE THREAD

**Issue by dlrepository** [Ricky12Awesome/curseforge_to_multimc#1]
Windows protect me and when i execute this do nothing did i need to have curseforge ?

**Comment by Ricky12Awesome** [comment]
Windows does that because the app isn't signed, signing costs money and I don't feel like doing it, you should just be able to ignore it and click "run anyway", and yes this app does need curseforge installed since all this app does is link the curseforge instance to MultiMC/PolyMC, I'll eventually get around improving the UI and support other launchers

**Comment by dlrepository** [comment]
Thanks for your help and your projet
